### ISSUE TITLE
PeppySpectrum standalone, just a black pygame window, no bars

### ISSUE THREAD

**Issue by Z8man** [project-owner/PeppySpectrum#1]
After installing PeppyMeter and got it to work great, I would like to implement PeppySpectrum standalone on a RPi5. 

Unfortunately I only see a black Pygame window after running the Spectrum.py code. No background, no bars, just a black screen. The Peppymeters work immediately if I start these on the same RPi5. 
The fifo, Myfifosa is filled and operates. When I test x, y values in the component.py code, these change (y), depending on the music. Unfortunately no image at all.
I have followed the code but was not able to find anything wrong with it. it seems the command "pygame.display.update(self.bounding_box)" in the update definition has no effect at all. In the Peppymeter code this works fine.
The component.py file is not able to draw anything of the screen.

Hope somebody can help me out.

**Comment by project-owner** [comment]
I believe you are using Pygame 2. It is more strict now regarding screen updates. It requires updates been done in the same thread where display was initialized. In the PeppySpectrum updates happen in a separate thread. I've recently refactored PeppyMeter to fix this issue. The PeppySpectrum was not refactored yet. The function self.clean_draw_update() should be called in the main event loop (start_display_output) instead of update_ui thread function.

**Comment by Z8man** [comment]
I put the self.clean_draw_update() command at the 3th last line in the (start_display_output) event loop and everything works like a dream. Thanks! This PeppySpectrum looks just like the PeppeMeters fantastic! Great work.
